"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const electron_1 = require("electron");
const path_1 = __importDefault(require("path"));
const process_1 = __importDefault(require("process"));
const FeatureFlags_1 = __importDefault(require("./FeatureFlags"));
const host_1 = require("./host");
const overlay_module_1 = __importDefault(require("./overlay_module"));
process_1.default.on('uncaughtException', (e) => {
    overlay_module_1.default.logMessage(`Overlay host process exception: ${e.message}`);
    overlay_module_1.default.logMessage(e.stack ?? '');
});
global.features = new FeatureFlags_1.default();
global.mainAppDirname = __dirname;
global.features.declareSupported('overlay-hidpi');
electron_1.app.disableHardwareAcceleration();
electron_1.app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required');
void electron_1.app.whenReady().then(() => {
    const buildInfo = require(path_1.default.join(process_1.default.resourcesPath, 'build_info.json'));
    require('discord_desktop_core/core.asar/app/discord_native/browser/accessibility');
    const app = require('discord_desktop_core/core.asar/app/discord_native/browser/app');
    app.injectBuildInfo(buildInfo);
    require('discord_desktop_core/core.asar/app/discord_native/browser/clipboard');
    require('discord_desktop_core/core.asar/app/discord_native/browser/constants');
    const { crashReporterSetup } = require('discord_desktop_core/core.asar/app/bootstrapModules/crashReporterSetup');
    crashReporterSetup.init(buildInfo);
    require('discord_desktop_core/core.asar/app/discord_native/browser/crashReporter');
    const features = require('discord_desktop_core/core.asar/app/discord_native/browser/features');
    features.injectFeaturesBackend(global.features);
    require('discord_desktop_core/core.asar/app/discord_native/browser/fileManager');
    require('discord_desktop_core/core.asar/app/discord_native/browser/gpuSettings');
    require('discord_desktop_core/core.asar/app/discord_native/browser/nativeModules');
    require('discord_desktop_core/core.asar/app/discord_native/browser/powerMonitor');
    require('discord_desktop_core/core.asar/app/discord_native/browser/powerSaveBlocker');
    require('discord_desktop_core/core.asar/app/discord_native/browser/processUtils');
    require('discord_desktop_core/core.asar/app/discord_native/browser/settings');
    require('discord_desktop_core/core.asar/app/discord_native/browser/spellCheck');
    require('discord_desktop_core/core.asar/app/discord_native/browser/window');
    require('discord_desktop_core/core.asar/app/discord_native/browser/hardware');
    overlay_module_1.default._initializeHostProcess({ createRenderer: host_1.createRenderer, destroyRenderer: host_1.destroyRenderer });
    overlay_module_1.default._setEventHandler(host_1.eventHandler);
});
